### ISSUE TITLE
Unexpected behavior when inserting with cur_size == max_size

### ISSUE THREAD

**Issue by florian1345** [paritytech/memory-lru#3]
# Error description

When `MemoryLruCache::insert` is called with a new key and some value and `cur_size` equals `max_size`, an element is dropped from the cache without its `resident_size` being accounted for. It appears that the developers mistakenly took the return value of `LruCache::put` to be whatever element was removed, however that is only the case if there was already an element with the given key present (see the [documentation](https://docs.rs/lru/0.6.6/lru/struct.LruCache.html#method.put)).

Note that this situation also causes elements to be dropped when entries with zero resident-size are added to a full cache.

# Reproduction

Consider the following test case. It is expected to pass, but it fails.

```rust
    impl ResidentSize for Vec<u8> {
        fn resident_size(&self) -> usize {
            self.len()
        }
    }

    #[test]
    fn it_does_not_work() {
        let mut cache = MemoryLruCache::new(8);
        cache.insert(1, vec![0u8, 1u8]);
        cache.insert(2, vec![2u8, 3u8]);
        cache.insert(3, vec![4u8, 5u8]);
        cache.insert(4, vec![6u8, 7u8]);
        cache.insert(5, vec![8u8, 9u8]);

        assert_eq!(Some(&vec![2u8, 3u8]), cache.get(&2));
    }
```

We can also observe that the `cur_size` is corrupted by this behavior. This is demonstrated by the test case below, which should fail, but passes.

```rust
    #[test]
    fn it_should_not_work() {
        let mut cache = MemoryLruCache::new(8);
        cache.insert(1, vec![0u8, 1u8]);
        cache.insert(2, vec![2u8, 3u8]);
        cache.insert(3, vec![4u8, 5u8]);
        cache.insert(4, vec![6u8, 7u8]);
        cache.insert(5, vec![8u8, 9u8]);

        let mut counted_size = 0;

        for i in 1..6 {
            if let Some(v) = cache.get(&i) {
                counted_size += v.resident_size();
            }
        }

        assert_eq!(6, counted_size);
        assert_eq!(8, cache.current_size());
    }
```

**Comment by ordian** [comment]
Thanks for the report!
If you're willing to submit a fix, we will accept it :)
